### ISSUE TITLE
Collaborate with us

### ISSUE THREAD

**Issue by steelbrain** [johanlunds/atom-ruby-debugger#1]
I am the author of the linter package. We're thinking of writing a base debugging interface provider now. Your experience from this package will be very helpful. Would you mind sharing your ideas about how that base provider's API should look like and about it's UI?

**Comment by johanlunds** [comment]
That sounds awesome! :+1: Unfortunately it's been some time since I last hacked on my package, so I think I've forgotten some.
- I've taken much UI- & feature-inspiration from the Chrome debugger which I like, so that's my main tip.
  - ... as well as some minor, less important ideas from Rubymine (can't remember which right now)
  - [You have a mockup of how I imagined the UI here](https://github.com/johanlunds/atom-ruby-debugger/blob/master/docs/moqup%20sketch%20ruby-debugger.pdf)
- API-wise: dunno, sorry to be of no help there.

Is there anywhere I can track the effort? I would like to follow it, and might help out in the future if I feel like it.

**Comment by johanlunds** [comment]
As a matter of fact, I unpublished the package, so if anyone else wants to write a Ruby-debugger the name should be available. No use having my non-functioning package there.

See https://github.com/johanlunds/atom-ruby-debugger/issues/2
